### ISSUE TITLE
Question - md5 is match with php function

### ISSUE THREAD

**Issue by FaShapouri** [mpurland/SwiftMD5#2]
The php MD5  has a optional parameter which is called  raw_output; This parameter set result of MD5 as binary; I need to know how can I change your implementation to get the result like the php MD5 when that parameter is true?
[Here](http://php.net/manual/en/function.md5.php) you can find the MD5 php document

**Comment by mpurland** [comment]
The md5Digest property on String should allow you return a Byte array representing the String. If you have data or bytes as input you can always use SwiftMD5.md5.

Let me know if this helps.

**Comment by FaShapouri** [comment]
I have used the lib you have provided; And I added a function to `String` extension which convert MD5 bytes to base64 and use it to get the result.
Thanks for your lib
